<x-app-layout :assets="$assets ?? []">
<div class="row"><div class="col-12"><div class="card rounded-4">
    <div class="card-header d-flex justify-content-between align-items-center flex-wrap gap-2"><div><h4 class="card-title mb-1">Expenses</h4><p class="mb-0 text-muted">Track project expenses from released CV records and store receipts.</p></div>@can('projects_mgmt.create')<a href="{{ route('project-expenses.create') }}" class="btn btn-sm btn-primary">Create Expense</a>@endcan</div>
    <div class="card-body">
        @if(session('success'))<div class="alert alert-success alert-dismissible fade show rounded-3 shadow-sm">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
        @if(session('error'))<div class="alert alert-danger alert-dismissible fade show rounded-3 shadow-sm">{{ session('error') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
        <x-wmc.datatable tableId="project-expenses-table" :columns="[['title'=>'CV #'],['title'=>'Store Name'],['title'=>'Store Receipts #'],['title'=>'Receipts Total Amount'],['title'=>'Status'],['title'=>'Actions']]" :hasFilter="true" filterId="expenseCvFilter">
            <x-slot name="filter"><div class="wmc-filter-ui"><label>Filter:</label><input type="hidden" id="expenseCvFilter" value=""><div class="btn-group wmc-clean-dropdown"><button type="button" class="btn wmc-clean-dropdown-main" id="expenseCvFilterText">All CV #</button><button type="button" class="btn wmc-clean-dropdown-toggle dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"><span class="visually-hidden">Toggle</span></button><ul class="dropdown-menu" style="max-height:240px;overflow-y:auto;"><li><a class="dropdown-item expense-cv-option" href="#" data-value="" data-label="All CV #">All CV #</a></li>@foreach($cvRecords as $rfp)<li><a class="dropdown-item expense-cv-option" href="#" data-value="{{ $rfp->id }}" data-label="CV {{ $rfp->cash_voucher_no }}">CV {{ $rfp->cash_voucher_no }}</a></li>@endforeach</ul></div></div></x-slot>
        </x-wmc.datatable>
    </div>
</div></div></div>
@push('scripts')
<script>
$(function(){
    let table=$('#project-expenses-table').DataTable({processing:false,serverSide:true,ajax:{url:"{{ route('project-expenses.list') }}",data:function(d){d.project_rfp_id=$('.filter-holder #expenseCvFilter').val();}},searchDelay:350,pageLength:10,lengthMenu:[10,25,50,100],dom:"<'row mb-3 align-items-center'<'col-lg-4'l><'col-lg-4 filter-holder'><'col-lg-4'f>><'row'<'col-sm-12'tr>><'row mt-3 align-items-center'<'col-sm-6'i><'col-sm-6'p>>",columns:[{data:'cv_no',name:'rfp.cash_voucher_no',render:d=>d||'-'},{data:'store_name',name:'storeName.name',render:d=>d||'-'},{data:'receipt_numbers',name:'receipts.store_receipt_no',render:d=>d||'-'},{data:'receipts_total_amount_formatted',name:'receipts_total_amount'},{data:'status_badge',name:'status'},{data:'action',name:'action',orderable:false,searchable:false}],order:[[0,'desc']],createdRow:function(row,data){if(data&&data.show_url)$(row).attr('title','Double-click to view expense');},initComplete:function(){$('.filter-holder').html($('#expenseCvFilterSource').html());$('#expenseCvFilterSource').remove();$('#project-expenses-table_filter input').attr('placeholder','Search Store Name or Receipt #');$(document).on('click','.filter-holder .expense-cv-option',function(e){e.preventDefault();$('.filter-holder #expenseCvFilter').val($(this).data('value'));$('.filter-holder #expenseCvFilterText').text($(this).data('label'));table.ajax.reload();});}});
    $('#project-expenses-table tbody').on('dblclick','tr',function(){let data=table.row(this).data();if(data&&data.show_url)window.location.href=data.show_url;});
    $(document).on('click','.delete-project-expense',function(e){e.preventDefault();e.stopPropagation();let form=$(this).closest('form');let name=$(this).data('name')||'this expense';Swal.fire({title:'Are you sure?',text:`Delete "${name}"?`,icon:'warning',showCancelButton:true,confirmButtonColor:'#d33',cancelButtonColor:'#6c757d',confirmButtonText:'Yes, delete it'}).then((r)=>{if(!r.isConfirmed)return;$.ajax({url:form.attr('action'),type:'POST',data:form.serialize(),dataType:'json',headers:{Accept:'application/json'},success:function(resp){table.ajax.reload(null,false);Swal.fire('Done',resp.message||'Expense deleted.','success');},error:function(xhr){Swal.fire('Error',xhr.responseJSON?.message||'Something went wrong.','error');}});});});
});
</script>
@endpush
</x-app-layout>
