@php
    $exportFormat = strtolower((string) ($exportFormat ?? request('format', 'print')));
    $reportCategories = [
        'summary' => ['title' => 'Attendance Summary'],
        'daily' => ['title' => 'Daily Attendance'],
        'employee' => ['title' => 'Employee Attendance'],
        'late_undertime' => ['title' => 'Late / Undertime'],
        'absences' => ['title' => 'Absences'],
        'holiday_pay' => ['title' => 'Holiday Pay'],
        'audit_trail' => ['title' => 'Audit Trail'],
    ];
    $activeReport = $reportCategories[$selectedReportType] ?? $reportCategories['summary'];
    $isExcel = $exportFormat === 'excel';
    $isPrintLike = in_array($exportFormat, ['print', 'pdf'], true);
    $generatedBy = auth()->user()->full_name ?? auth()->user()->name ?? 'HR Admin';
    $generatedAt = now()->format('M j, Y h:i A');
    $reportTitle = strtoupper($activeReport['title']) . ' REPORT';

    if ($selectedReportType === 'daily') {
        $detailRows = $dailyRows;
        $detailMode = 'daily';
    } elseif ($selectedReportType === 'late_undertime') {
        $detailRows = $lateUndertimeRows;
        $detailMode = 'late';
    } elseif ($selectedReportType === 'absences') {
        $detailRows = $absenceRows;
        $detailMode = 'daily';
    } elseif ($selectedReportType === 'holiday_pay') {
        $detailRows = $holidayRows;
        $detailMode = 'holiday';
    } else {
        $detailRows = collect();
        $detailMode = null;
    }
@endphp
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $activeReport['title'] }}</title>
    <style>
        @page { size: landscape; margin: 9mm; }
        * { box-sizing: border-box; }
        html, body { margin: 0; padding: 0; background: #ffffff; color: #0f172a; font-family: Arial, Helvetica, sans-serif; font-size: 11px; }
        .report-shell { width: 100%; padding: 14px; }
        .report-header { text-align: center; margin-bottom: 16px; }
        .report-title { margin: 0 0 5px; font-size: 22px; font-weight: 800; letter-spacing: 1.5px; }
        .report-period { font-size: 13px; font-weight: 700; color: #475569; margin-bottom: 3px; }
        .report-filter { font-size: 11px; color: #64748b; }
        .meta-row { width: 100%; margin: 16px 0 12px; border-collapse: collapse; }
        .meta-row td { border: 0; padding: 0; font-size: 11px; color: #475569; }
        .meta-row .right { text-align: right; }
        .report-table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        .report-table th, .report-table td { border: 1px solid #d8e0ec; padding: 6px 7px; vertical-align: middle; word-wrap: break-word; overflow-wrap: break-word; }
        .report-table th { background: #f3f6fb; text-transform: uppercase; font-size: 10px; line-height: 1.15; letter-spacing: .35px; text-align: center; font-weight: 800; }
        .report-table td { font-size: 10.5px; line-height: 1.25; }
        .report-table tfoot td { background: #f8fafc; font-weight: 800; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .fw-bold { font-weight: 800; }
        .empty-row { text-align: center; color: #64748b; padding: 18px !important; }
        .signature-row { width: 100%; margin-top: 42px; border-collapse: collapse; }
        .signature-row td { border: 0; padding: 0; width: 50%; text-align: center; }
        .signature-line { display: inline-block; width: 260px; border-top: 1px solid #0f172a; padding-top: 7px; font-weight: 700; }
        .no-print { margin-bottom: 12px; text-align: right; }
        .no-print button { border: 1px solid #64748b; background: #fff; border-radius: 8px; padding: 7px 12px; cursor: pointer; }
        @media print {
            .no-print { display: none !important; }
            html, body { width: 100%; }
            .report-shell { padding: 0; }
            .report-table th { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
</head>
<body @if($isPrintLike) onload="setTimeout(function(){ window.print(); }, 250)" @endif>
    <div class="report-shell">
        @if($isPrintLike)
            <div class="no-print"><button type="button" onclick="window.print()">Print / Save as PDF</button></div>
        @endif

        <div class="report-header">
            <h1 class="report-title">{{ $reportTitle }}</h1>
            <div class="report-period">{{ $cutoffStart->format('M j') }} - {{ $cutoffEnd->format('M j, Y') }} ({{ $periodLabel }})</div>
            <div class="report-filter">{{ $branchName }} &bull; {{ $departmentName }}</div>
        </div>

        <table class="meta-row">
            <tr>
                <td>Generated By: {{ $generatedBy }}</td>
                <td class="right">Date Generated: {{ $generatedAt }}</td>
            </tr>
        </table>

        @if(in_array($selectedReportType, ['daily', 'late_undertime', 'absences', 'holiday_pay'], true))
            <table class="report-table">
                <colgroup>
                    <col style="width:4%;">
                    <col style="width:9%;">
                    <col style="width:16%;">
                    <col style="width:13%;">
                    <col style="width:11%;">
                    <col style="width:11%;">
                    <col style="width:8%;">
                    <col style="width:8%;">
                    <col style="width:8%;">
                    <col style="width:12%;">
                </colgroup>
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Date</th>
                        <th>Employee Name</th>
                        <th>Designation</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                        <th>Status</th>
                        <th>Late<br>(min)</th>
                        <th>Undertime<br>(min)</th>
                        <th>@if($detailMode === 'holiday') Holiday Pay @else Remarks @endif</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($detailRows as $i => $row)
                        <tr>
                            <td class="text-center">{{ $i + 1 }}</td>
                            <td class="text-center">{{ $row['date']->format('M j, Y') }}</td>
                            <td>{{ $row['employee_name'] }}</td>
                            <td>{{ $row['designation'] }}</td>
                            <td class="text-center">{{ $row['time_in'] ?: '—' }}</td>
                            <td class="text-center">{{ $row['time_out'] ?: '—' }}</td>
                            <td class="text-center">{{ $row['status_label'] }}</td>
                            <td class="text-center">{{ number_format($row['late_minutes']) }}</td>
                            <td class="text-center">{{ number_format($row['undertime_minutes']) }}</td>
                            <td>@if($detailMode === 'holiday') ₱{{ number_format($row['holiday_pay'], 2) }} @else {{ $row['remarks'] ?: '—' }} @endif</td>
                        </tr>
                    @empty
                        <tr><td colspan="10" class="empty-row">No attendance records found for the selected filters.</td></tr>
                    @endforelse
                </tbody>
            </table>
        @elseif($selectedReportType === 'audit_trail')
            <table class="report-table">
                <thead>
                    <tr>
                        <th style="width:6%;">No.</th>
                        <th>Activity</th>
                        <th style="width:14%;">Report Type</th>
                        <th style="width:20%;">Date/Time</th>
                        <th style="width:18%;">Generated By</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($lastGeneratedReports as $i => $generated)
                        <tr>
                            <td class="text-center">{{ $i + 1 }}</td>
                            <td>{{ $generated['title'] }}</td>
                            <td class="text-center">{{ $generated['type'] }}</td>
                            <td class="text-center">{{ $generated['time'] }}</td>
                            <td>{{ $generatedBy }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="empty-row">No generated report activity found.</td></tr>
                    @endforelse
                </tbody>
            </table>
        @else
            <table class="report-table">
                <colgroup>
                    <col style="width:4%;">
                    <col style="width:16%;">
                    <col style="width:14%;">
                    <col style="width:8%;">
                    <col style="width:8%;">
                    <col style="width:8%;">
                    <col style="width:8%;">
                    <col style="width:7%;">
                    <col style="width:8%;">
                    <col style="width:9%;">
                    <col style="width:10%;">
                </colgroup>
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Employee Name</th>
                        <th>Designation</th>
                        <th>Rate/Day</th>
                        <th>Rate/Hour</th>
                        <th>Present<br>Days</th>
                        <th>Absent<br>Days</th>
                        <th>Late<br>(min)</th>
                        <th>Undertime<br>(min)</th>
                        <th>Holiday<br>Pay</th>
                        <th>Grand Total</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($rows as $row)
                        <tr>
                            <td class="text-center">{{ $row['no'] }}</td>
                            <td>{{ $row['employee_name'] }}</td>
                            <td>{{ $row['designation'] }}</td>
                            <td class="text-right">₱{{ number_format($row['rate_day'], 2) }}</td>
                            <td class="text-right">₱{{ number_format($row['rate_hour'], 2) }}</td>
                            <td class="text-center">{{ number_format($row['present_days'], 1) }}</td>
                            <td class="text-center">{{ number_format($row['absent_days'], 1) }}</td>
                            <td class="text-center">{{ number_format($row['late_minutes']) }}</td>
                            <td class="text-center">{{ number_format($row['undertime_minutes']) }}</td>
                            <td class="text-right">₱{{ number_format($row['holiday_pay'], 2) }}</td>
                            <td class="text-right fw-bold">₱{{ number_format($row['grand_total'], 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="11" class="empty-row">No attendance records found for the selected filters.</td></tr>
                    @endforelse
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5" class="text-right">TOTAL</td>
                        <td class="text-center">{{ number_format($totals['present_days'], 1) }}</td>
                        <td class="text-center">{{ number_format($totals['absent_days'], 1) }}</td>
                        <td class="text-center">{{ number_format($totals['late_minutes']) }}</td>
                        <td class="text-center">{{ number_format($totals['undertime_minutes']) }}</td>
                        <td class="text-right">₱{{ number_format($totals['holiday_pay'], 2) }}</td>
                        <td class="text-right">₱{{ number_format($totals['grand_total'], 2) }}</td>
                    </tr>
                </tfoot>
            </table>
        @endif

        <table class="signature-row">
            <tr>
                <td><span class="signature-line">Prepared By</span></td>
                <td><span class="signature-line">Approved By</span></td>
            </tr>
        </table>
    </div>
</body>
</html>
